[package]
name = "ergodox-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
rusb = "0.9"
indicatif = "0.17"
anyhow = "1"
ergodox-keymap = { path = "../ergodox-keymap" }
